[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
market_tick = "Fg6PaFpoGXkYsidMpWxTWqkZK6W2BeZ7FEfcYkgMQhg"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["market-tick"]
